require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'config/initializers/devise.rb'

# Prefer modern Ruby style
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Allow longer lines for readability
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

# Allow longer methods in tests
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'db/seeds.rb'

# Documentation not required for demo
Style/Documentation:
  Enabled: false

# RSpec-specific configurations
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# Rails-specific configurations
Rails/I18nLocaleTexts:
  Enabled: false
