require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'config/initializers/devise.rb'
    - 'lib/tasks/cucumber.rake'

# Disable line ending checks (cross-platform compatibility)
Layout/EndOfLine:
  Enabled: false

# Prefer modern Ruby style
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Allow longer methods in tests
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'
    - 'db/seeds.rb'

# Documentation not required for demo
Style/Documentation:
  Enabled: false

# RSpec-specific configurations
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

# Rails-specific configurations
Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

# Disable some overly strict cops
Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/**/*'
    - 'features/**/*'

# Script permissions not relevant on Windows
Lint/ScriptPermission:
  Enabled: false

# Allow empty blocks in cucumber tasks
Lint/EmptyBlock:
  Exclude:
    - 'lib/tasks/cucumber.rake'

# Disable Style/NumericPredicate in Cucumber steps (causes issues with RSpec matchers)
Style/NumericPredicate:
  Exclude:
    - 'features/**/*'
